disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- count_violation
- function_parameter_count
- identifier_name
- type_body_length
- file_length
- type_name
