# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
workspace 'Dicoding'

target 'GameAppExpert' do
  pod 'Cosmos', '~> 23.0'
  pod 'Reusable'
  pod 'Alamofire'
end

target 'Favorite' do
  project '../Modules/Favorite/Favorite'
end

target 'About' do
  project '../Modules/About/About'
end

target 'Home' do
  project '../Modules/Home/Home'
  pod 'Cosmos', '~> 23.0'
  pod 'Reusable'
  pod 'Alamofire'
end

target 'Detail' do
  project '../Modules/Detail/Detail'
end
